from tkinter import*
a = Tk()
a.title("SHOP INFO")
#a.iconbitmap("shop.ico")
shop_name = Label(a,text = "KAPOOR GARMENT", fg = "red")
shop_add = Label(a,text = "1,kotha Parcha,Alld", fg = "red")
shop_mobile = Label(a,text = "09876543211", fg = "red")
shop_state = Label(a,text = "UTTAR PRADESH", fg = "red")
cuname_label = Label(a,text = "Customer Name" , fg = "white" , bg = "black").grid(row = 4 , column = 0 , padx = 6 , pady = 6 , ipadx = 7 , ipady = 7)
cuname_box = Entry(a).grid(row = 4 , column = 1 , padx = 4 , pady = 4 , ipadx = 6 , ipady = 6)
mobile_label = Label(a,text = "Customer mobile no." , fg = "white" , bg = "black").grid(row = 5 , column = 0 , padx = 2 , pady = 2 , ipadx = 6 , ipady = 6)
mobile_box = Entry(a).grid(row = 5 , column = 1 , padx = 4 , pady = 4 , ipadx = 6 , ipady = 6)
total_label = Label(a,text = "Total Amount" , fg = "white" , bg = "black").grid(row = 16 , column = 1 , padx = 4 , pady = 4 , ipadx = 5 , ipady = 5)
total_box = Entry(a).grid(row = 16 , column = 2  , padx = 4 , pady = 4 , ipadx = 5 , ipady = 5)
item_label = Label(a,text = "ITEM", fg = "red").grid(row = 9 , column = 1, padx = 4, pady = 4, ipadx = 5 , ipady = 5)
name_label = Label(a,text = "NAME", fg = "white", bg = "black").grid(row =10 , column =1, padx =8 , pady =8 , ipadx =5 , ipady =5)
rate_label = Label(a,text = "RATE", fg = "white", bg = "black").grid(row =10 , column =2 , padx =8 , pady =8 , ipadx =5 , ipady =5)
discount_label = Label(a,text = "DISCOUNT", fg = "white", bg = "black").grid(row =17 , column =1 , padx =8 , pady =8 , ipadx =5 , ipady =5)
discount_box = Entry(a)
discount_box.grid(row =17 , column =2 , padx =8 , pady =8 , ipadx =5 , ipady =5)
a.mainloop()
