from Tkinter import *
a =Tk()
a.title("options")

product=["Python","PHP","Android","ASP.NET","Bootstrap"]
price={"Python":5500,"PHP":5500,"Android":5000,"ASP.NET":7000,"Bootstrap":3500}

name_label = Label(a,text = "Name").grid(row = 0 , column = 0 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
name_box = Entry(a).grid(row = 0 , column = 1 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
mobile_label = Label(a,text = "Mobile").grid(row = 0 , column = 2 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
mobile_box = Entry(a).grid(row = 0 , column = 3 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
add_button = Button(a,text = "Add")
add_button.grid(row = 3 ,column = 1 ,padx = 4 ,pady = 4)
product_button = Button(a,text = "Product")
product_button.grid(row = 3 , column = 0 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
price_label = Label(a,text = "Price")
price_label.grid(row = 3 , column = 2 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
p1_box = Entry(a)
p1_box.grid(row = 4 , column = 0 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
p2_box = Entry(a)
p2_box.grid(row = 5 , column = 0 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
p3_box = Entry(a)
p3_box.grid(row = 6 , column = 0 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
p4_box = Entry(a)
p4_box.grid(row = 7 , column = 0 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
p5_box = Entry(a)
p5_box.grid(row = 8 , column = 0 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
price1_box = Entry(a)
price1_box.grid(row = 4 , column = 2 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
price2_box = Entry(a)
price2_box.grid(row = 5 , column = 2 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
price3_box = Entry(a)
price3_box.grid(row = 6 , column = 2 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
price4_box = Entry(a)
price4_box.grid(row = 7 , column = 2 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
price5_box = Entry(a)
price5_box.grid(row = 8 , column = 2 , padx = 4 , pady = 4 , ipadx = 4 , ipady = 4)
a.mainloop()
